### ISSUE TITLE
Feature - support category and Quality in backup/restore

### ISSUE THREAD

**Issue by neutrongenious** [clinton-hall/CP-BackupTool#18]
CouchPotato allows you to specify Quality and Category for wanted list. it would be great if an option allows to store quality and Category for both backup and restore.

**Comment by peerster** [comment]
The latest build should already do this. I don't remember if it both or just quality though. I'm not able to test this right now. I will check when I can

**Comment by peerster** [comment]
@neutrongenious Qualty is already backed up. Catagory isn't chosen per wanted movie and to me it doesn't make sense to try to include it in this backup/restore script

**Comment by clinton-hall** [comment]
Is it possible to actually rebuild the quality profiles and categories in the database (not applying them to the restored movies) but to allow the required, ignored, preferred words and the category destinations to the database?

Basically, these are the 2 "settings" that aren't saved in settings.conf, and there can be some significant information that is hard to rebuild (the ignored and required words etc).

I haven't looked at the api tosee what category and quality information can be retrieved.

**Comment by peerster** [comment]
@clinton-hall I don't know. I think for this to work we need to include it in the backup process, which will require knowledge of the database etc.

Qualitiy ID is stored with the wanted movie (and it's included in the backup).
The ID of the quality however is most likely a random hash when the quality was created.
So if you would reinstall CP and create the same Quality, I'm not sure it will have the same quality hash. I can try to figure this out though.
