### ISSUE TITLE
CP backup cuts off at 201 titles

### ISSUE THREAD

**Issue by MiG29** [clinton-hall/CP-BackupTool#24]
D:\TEMP\CP_Wanted_List>wanted.py --type backup --file backup.txt
Loading config from: D:\TEMP\CP_Wanted_List\couch.cfg
Opening URL: http://localhost:5050/api/(api key)/movie.list/?status=active
found 201 wanted movies, writing file...
Backup file completed: backup.txt

Subsequent file indeed contains 201 titles. I've used excel to count the number of lines in the wanted list interface, and that nets about 1200 titles, five times as many.

**Comment by peerster** [comment]
I can take a look at it,  but it sounds wierd. It might be something with the api.

**Comment by MiG29** [comment]
One thing I've noticed is the resulting file size seems to be right below 10kb every time: 10251 bytes and 10200 bytes at the last (separate) two attempts. Nothing in the logs though, not even when turning on debugging.

**Comment by peerster** [comment]
I'll will try to reproduce it. Just have to figure out how to add 201 titles in a easy way :)

**Comment by peerster** [comment]
Can't reproduce.

Try a backup with 250 wanted movies
```
$ ./wanted.py --cfg /home/test/.couchpotato/settings.conf --type backup --file /tmp/test.txt
Loading config from: /home/test/.couchpotato/settings.conf
No 'host' found in config, using default: 'localhost'
Opening URL: http://localhost:5051/api/4e4d579b01c347b98d175f9a9e757327/movie.list/?status=active
found 250 wanted movies, writing file...
Backup file completed: /tmp/test.txt
$ ls -lhtr /tmp/test.txt
-rw-rw-r--. 1 test test 13K Apr  5 18:03 /tmp/test.txt
```

Remove all wanted movies
```
$ ./wanted.py --cfg /home/test/.couchpotato/settings.conf --type delete
Loading config from: /home/test/.couchpotato/settings.conf
No 'host' found in config, using default: 'localhost'
Opening URL: http://localhost:5051/api/4e4d579b01c347b98d175f9a9e757327/movie.list/?status=active
Deleting wanted movies...
[...]
```

Restore the wanted movies from backup
```
$ ./wanted.py --cfg /home/test/.couchpotato/settings.conf --type restore --file /tmp/test.txt
Loading config from: /home/test/.couchpotato/settings.conf
No 'host' found in config, using default: 'localhost'
Doing a full managed scan...
[...]
```

And try a backup once again
```
$ ./wanted.py --cfg /home/test/.couchpotato/settings.conf --type backup --file /tmp/test.txt
Loading config from: /home/test/.couchpotato/settings.conf
No 'host' found in config, using default: 'localhost'
Opening URL: http://localhost:5051/api/4e4d579b01c347b98d175f9a9e757327/movie.list/?status=active
found 250 wanted movies, writing file...
Backup file completed: /tmp/test.txt
```

FYI: You don't have to count in the GUI the number of wanted files, it shows 
![ss](https://cloud.githubusercontent.com/assets/5441497/6997557/ca2a5ec6-dbbf-11e4-8a1c-c54acb533def.PNG)

**Comment by MiG29** [comment]
Strange, that shows '200 movies' here (instead of the full 1200). I'm guessing db issues of some sort, and if so, what's the best way to still make that backup? The reason I'm trying to make that backup is because some movies refused to be removed from the wanted list.

**Comment by peerster** [comment]
No idea I'm afraid.  Maybe use the forum or file a bug on couchpotato Github if you have an error that you can see I logs and can reproduce.
