### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by scatteril** [clinton-hall/CP-BackupTool#25]
hello.
I dont know I can not get it right to work it always says an error .

usage: wanted.py [-h] --type backup/restore/delete [--file FILE]
                 [--cfg cfg-file]
wanted.py: error: argument --type is required

>>> backup "C:\Users\-Scatteril\Documents\wanted backup.txt"
SyntaxError: invalid syntax

what is happening ?

**Comment by peerster** [comment]
As it states, you need to specify --type. Valid types are backup, restore or delete (also specified in the help output)

**Comment by scatteril** [comment]
I have specified the type which is backup before the path . Im i doing it wrong ?

**Comment by peerster** [comment]
Example:
```wanted.py --type backup --cfg your_cfg my_wanted_backup.txt```

**Comment by scatteril** [comment]
>>> wanted.py --type backup --cfg C:\Users-Scatteril\Documents\wanted backup.txt
SyntaxError: invalid syntax
>>> wanted.py --type backup --cfg "C:\Users-Scatteril\Documents\wanted backup.txt"
SyntaxError: invalid syntax

The word backup is marked by red color

**Comment by peerster** [comment]
My guess is that "C:\Users-Scatteril\Documents\wanted backup.txt" isn't your cfg, but rather the file you want to backup to.

So, change it to this and it should work:
```wanted.py --type backup --cfg <the path to your couchpotato.cfg> "C:\Users-Scatteril\Documents\wanted backup.txt"```

**Comment by scatteril** [comment]
still invalid syntax marking the marking the word backup

wanted.py --type backup --cfg C:\Users\-Scatteril\AppData\Roaming\CouchPotato\settings.conf "C:\Users-Scatteril\Documents\wanted backup.txt"
SyntaxError: invalid syntax

**Comment by scatteril** [comment]
![screenshot 2015-04-22 16 00 39](https://cloud.githubusercontent.com/assets/6876676/7274844/fd912dc0-e908-11e4-9d28-cd515cbb142d.png)

**Comment by peerster** [comment]
Ok. I have to test this on windows

**Comment by seanvree** [comment]
Hey @peerster , I'm getting this same error on Windows.  Running within a Dos Prompt.

Tried every single variant possible. Something is wrong with the syntax. 

I have a windows machine, you're welcome to RDP. #

**Comment by clinton-hall** [comment]
via Dos prompt, if Python is not in the system path with the .py registered as executable, you probably need to call python first...

`C:/Python/python.exe wanted.py --type backup --cfg C:\Users\-Scatteril\AppData\Roaming\CouchPotato\settings.con`

or similar.... not able to check on a windows system right now.

**Comment by peerster** [comment]
@clinton-hall beat me to it.

The SyntaxError @scatteril showed was due to syntax error in the python console
But to demonstrate in Linux:
```
$ python
Python 2.7.5 (default, Sep 15 2016, 22:37:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> ./wanted.py # <-- not a valid syntax
  File "<stdin>", line 1
    ./wanted.py # <-- not a valid syntax
    ^
SyntaxError: invalid syntax
```

The correct way to execute the script:
```
$ python wanted.py 
usage: wanted.py [-h] --type backup/restore/delete [--file FILE]
                 [--cfg cfg-file]
wanted.py: error: argument --type is required
```
As you can see, the script will not give you SyntaxError. If you have wrong arguments and/or values to the script, it will tell you so

**Comment by seanvree** [comment]
@clinton-hall, @peerster 

Python IS in the system path, I run it all day.  Like I said, you're welcome to RDC into my server if you'd like to do some testing

**Comment by peerster** [comment]
@seanvree Ok. 
Sorry to hear that you have this problem. I would suggest giving a bit more info (like the exact way you execute the script etc...). That said I don't use this script anymore, and don't have time to maintain it. Either @clinton-hall will have to help, or you can try to solve it yourself

**Comment by seanvree** [comment]
Okay, here are the steps:


Ensure you have Python added to PATH


Run CMD.exe as administrator 

CD C:\CP-BackupTool [github clone repository]

wanted.py --type backup --file C:\CouchPotato\wantedbackup.txt [output file]

**Comment by peerster** [comment]
Do you get the same error if you specify the --cfg <path to cfg> ?

**Comment by seanvree** [comment]
Yes.

**Comment by peerster** [comment]
What does [output file] mean in your example?

**Comment by seanvree** [comment]
That's where the database backeup text file goes.

**Comment by peerster** [comment]
But you have specified it already with --file option with value `C:\CouchPotato\wantedbackup.txt"`.

**Comment by seanvree** [comment]
Oh......I see what you're saying, NO, I put "[output]" file to show that's the path where the backup text file goes.

**Comment by peerster** [comment]
This is the way I run it:
```
$ ./wanted.py --type backup --cfg /home/my-user/.couchpotato/settings.conf --file /home/my-user/backup/cp_backup.txt
```
Sorry, still don't understand what you mean with [output file]

**Comment by seanvree** [comment]
Umm, that is the PATH where the backed-up database is stored!!!

**Comment by peerster** [comment]
Still don't get it.

**Comment by seanvree** [comment]
LOL, I don't know what to tell you man.  I ran the commands above and it worked.

**Comment by clinton-hall** [comment]
you are saying that the location specified after `--file` is the output file? I believe the confusion here is that it looks like you are issuing the command `[output file]`

Can you send me the RDP details?

**Comment by seanvree** [comment]
Right, [output file] is NOT a command, it was my way of expressing that that directory is supposed to be targeted to whatever location they want the databas-backup file stored. 

Na, I got it to work man, It's pretty simple.  Bed time.

**Comment by clinton-hall** [comment]
ok.. good job.

**Comment by seanvree** [comment]
Yup, if you want to include that in your instructions, it's VERY simple. Just remove the CFG part, and ensure the user edits the CP-backup-tool config file manually. 

Cheers

**Comment by yirrlaar** [comment]
Resurrecting this issue ... running Windows 7

C:\Program Files\Python36>python wanted.py --type backup --cfg "C:\Users\Merlin\AppData\Roaming\CouchPotato\settings.conf" "C:\wanted backup.txt"
  File "wanted.py", line 32
    print "No '%s' found in config, using default: '%s'" % (item, default_host)
                                                       ^
SyntaxError: invalid syntax

**Comment by peerster** [comment]
The tool doesn't work for python3

**Comment by yirrlaar** [comment]
Thanks but now I'm getting

C:\Python27>python wanted.py --type backup --file "C:\backup.txt"
Loading config from: couch.cfg
Opening URL: http://localhost:5050/api/d358d0fa53a66a5bc8d8c7bcf2857219/movie.list/?status=active
Traceback (most recent call last):
  File "wanted.py", line 264, in <module>
    process(args.type, args.file)
  File "wanted.py", line 116, in process
    if result['total'] > 0:
KeyError: 'total'
