### ISSUE TITLE
Skip library update

### ISSUE THREAD

**Issue by theCheek** [clinton-hall/CP-BackupTool#28]
Hi, long time CP user, many thanks for the work. 

I am tying to use this tool to sync my wanted movies of my seedbox to my wanted movies of my NAS, as the two are connected via BTSync, with my NAS' CP being used just for the renamer functionality. Basically I want to set up a cron job to run CP Backup on my seedbox, then the .txt file is synced to my NAS, where another cronjob runs a restore job.

The issue is that because of my large library on my NAS, the fact that the restore tool initiates a full library scan makes the restore process take up to 12 hours. 

Is it absolutely necessary to have it perform the library scan before a restore? Is there any way to disable it?

**Comment by clinton-hall** [comment]
try updating to latest version, then use option "add" not "restore".

**Comment by theCheek** [comment]
awesome thanks!
Just ran it and it seem to work perfectly. Do you think it matters if some movies have already been added before running the tool? Doesn't seem to matter but just wanted to check.

**Comment by clinton-hall** [comment]
Shouldn't matter. I had thought about this and wondered if there should be a "sync" option to ignore movies common to both lists (and maybe even delete movies in the wanted list that aren't in the text... So if a movie was downloaded already).

Perhaps this could sync directly between 2 CP servers?... But that is a bit more work. This fix should do what you need.

**Comment by theCheek** [comment]
Ok perfect. Thanks again for your ongoing commitment to a wonderful bit of software!
