### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by cddude** [clinton-hall/CP-BackupTool#33]
I am moving from one computer to a new one.  I have successfully exported into a txt file but can't for the life of me import into the new one.  How do I fix this?  I've pasted below what Terminal tells me...

P.S. I tried the whole reformatting the .txt file as...
[
["tt2250912",""],
["tt5657577",""],
.....
["tt5757775",""]
]

Error code....

Jeremys-MBP:~ edmonds$ /Users/edmonds/Documents/Inbox/CP-BackupTool-master/wanted.py --type restore --file /Users/edmonds/Documents/Inbox/backup2.txt
Loading config from: /Users/edmonds/Documents/Inbox/CP-BackupTool-master/couch.cfg
Doing a full managed scan...
Opening URL: http://localhost:5050/api/44602ed6bd964709b493b8b6e280cd27/manage.update/?full=1
Traceback (most recent call last):
  File "/Users/edmonds/Documents/Inbox/CP-BackupTool-master/wanted.py", line 262, in <module>
    process(args.type, args.file)
  File "/Users/edmonds/Documents/Inbox/CP-BackupTool-master/wanted.py", line 147, in process
    result = apiCall(url)
  File "/Users/edmonds/Documents/Inbox/CP-BackupTool-master/wanted.py", line 55, in apiCall
    result = json.load(urlObj)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by clinton-hall** [comment]
What happens if you open `http://localhost:5050/api/44602ed6bd964709b493b8b6e280cd27/manage.update/?full=1` in your browser?

**Comment by cddude** [comment]
It says "Wrong API key used"

**Comment by cddude** [comment]
I just went into CP on the new computer that i'm trying to import/restore to and grabbed the API key there and replaced it in that url.  Now it says... 

{"progress": false, "success": true}

**Comment by clinton-hall** [comment]
ok... so that api key is what need to be put into the `/Users/edmonds/Documents/Inbox/CP-BackupTool-master/couch.cfg`

i.e. this config needs to point to your new set-up, or alternately run

`/Users/edmonds/Documents/Inbox/CP-BackupTool-master/wanted.py --type restore --cfg /your/path/.couchpotato/settings.conf --file /Users/edmonds/Documents/Inbox/backup2.txt`

where obviously you need to replace `/your/path/.couchpotato/settings.conf` with the actual path to the NEW CouchPotato settings.conf

**Comment by cddude** [comment]
ok I will try that and get back to here.

**Comment by cddude** [comment]
I used this command "/Users/edmonds/Documents/Inbox/+\ MIGRATION/CP-BackupTool-master/wanted.py --type restore --file /Users/edmonds/Documents/Inbox/+\ MIGRATION/backup3.txt" and it's running but seems to be hanging.  it says...

Loading config from: /Users/edmonds/Documents/Inbox/+ MIGRATION/CP-BackupTool-master/couch.cfg
Doing a full managed scan...
Opening URL: http://localhost:5050/api/f0995491884b4185b96023b7fe5956d6/manage.update/?full=1
Opening URL: http://localhost:5050/api/f0995491884b4185b96023b7fe5956d6/manage.progress

**Comment by cddude** [comment]
Crap.  It failed again.  Here's the full string.

/Users/edmonds/Documents/Inbox/+\ MIGRATION/CP-BackupTool-master/wanted.py --type restore --file /Users/edmonds/Documents/Inbox/+\ MIGRATION/backup3.txt
Loading config from: /Users/edmonds/Documents/Inbox/+ MIGRATION/CP-BackupTool-master/couch.cfg
Doing a full managed scan...
Opening URL: http://localhost:5050/api/f0995491884b4185b96023b7fe5956d6/manage.update/?full=1
Opening URL: http://localhost:5050/api/f0995491884b4185b96023b7fe5956d6/manage.progress
Managed scan completed
Traceback (most recent call last):
  File "/Users/edmonds/Documents/Inbox/+ MIGRATION/CP-BackupTool-master/wanted.py", line 262, in <module>
    process(args.type, args.file)
  File "/Users/edmonds/Documents/Inbox/+ MIGRATION/CP-BackupTool-master/wanted.py", line 159, in process
    movie_list = json.load(f)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by cddude** [comment]
Same error "{"progress": false, "success": true}"

**Comment by cddude** [comment]
checked again and now it says...

{"progress": {"/Volumes/Extra Storage 2/Movies": {"eta": 0, "to_go": 0, "started": 1497552452, "total": 299}, "/Volumes/Extra Storage 2/Movies For Kids": {"eta": 0, "to_go": 0, "started": 1497552424, "total": 87}, "/Volumes/Extra Storage 2/TEMPORARY/Movies": {"eta": 107, "to_go": 285, "started": 1497552498, "total": 322}}, "success": true}
0


which is weird because those folders are the folder where the Manage section is pointed to which is different than Wanted

**Comment by cddude** [comment]
Ran the command again and now we are back to {"progress": false, "success": true}

**Comment by cddude** [comment]
Can I get some more help with this?

**Comment by clinton-hall** [comment]
I think the issue now is that you edited the .txt file, so this is not being correctly loaded.
firstly, this should not be edited via notepad as this introduces windows style carriage returns, and this should be in the original format of
```
[["tt2250912",""], ["tt5657577",""], ....., ["tt5757775",""]]
```

**Comment by cddude** [comment]
I'm editing with textedit on mac.  are you saying by your example that the second quotation marks should be empty or is that where the api should be?

**Comment by cddude** [comment]
[backup.txt](https://github.com/clinton-hall/CP-BackupTool/files/1086822/backup.txt)
[backup2.txt](https://github.com/clinton-hall/CP-BackupTool/files/1086823/backup2.txt)
Here's two examples.  One with no returns, another with returns added through textedit.

**Comment by cddude** [comment]
p.s. the reason i'm doing this is moving from old computer to new computer.  so i have to edit the file because i have to change the API.

**Comment by clinton-hall** [comment]
You shouldn't need to edit the backup.txt at all. The second "" shouldn't contain the apikey, they should contain some information about the id of the movie in the original database. In either case, that shouldn't be needed.

The api key is either obtained from the couch.cfg or the couchpotato settings.conf if you use option --cfg /your/path/.couchpotato/settings.conf

the error you have above says that it can't load json data from your backup.txt. this file should have been saved as json when you ran this script on your old installation.

**Comment by clinton-hall** [comment]
I get the same error as you `ValueError: No JSON object could be decoded` when using your backup2.txt, but when I use backup.txt this works.

**Comment by cddude** [comment]
if the "" shouldn't contact the apikey then why was it inserted when I exported it to begin with?  That is the exact txt file your process spit out when i followed the steps.  What's in that second "" on backup.txt is the api key of CP from the old computer.

can you list the settings.conf commands again?  i'll try that

**Comment by cddude** [comment]
also how do i find where my path is to settings.conf on this computer for CP?

**Comment by cddude** [comment]
i think i got it to work!  but it's missing all of the quality references.

**Comment by clinton-hall** [comment]
This doesn't restore the quality, since the quality is relative to the quality profiles on each setup and uses database references...

This Idea is to restore the wanted list. From there you can bulk-assign to qualities/profiles and categories.

**Comment by cddude** [comment]
Perfect thanks!  I think i'm finally good to go.
