### ISSUE TITLE
KeyError: 'movie'

### ISSUE THREAD

**Issue by yakaman** [clinton-hall/CP-BackupTool#34]
Hi,

I'm trying to export my library and get this error:

> /home/couchpotato/CP-BackupTool# ./wanted.py --type export --file export.txt
> Loading config from: ./couch.cfg
> Opening URL: http://localhost:5050/api/123456789/movie.list/?status=done
> Traceback (most recent call last):
>   File "./wanted.py", line 262, in <module>
>     process(args.type, args.file)
>   File "./wanted.py", line 231, in process
>     movie_list.append(release["files"]["movie"][0])
> KeyError: 'movie'
> 

Any suggestions ?

Thanks.

**Comment by clinton-hall** [comment]
What happens if you access the url manually?
`http://localhost:5050/api/123456789/movie.list/?status=done`

Post some of the output to see what is happening.

**Comment by yakaman** [comment]
The output is JSON as expected:
`{
	"movies": [{
			"status": "done",
			"info": {
				"rating": {
					"imdb": [7.3, 157082]
				},
				"genres": ["Horror", "Science Fiction", "Drama", "Mystery", "Thriller"],
				"tmdb_id": 333371,
				"plot": "Waking up from a car accident, a young woman finds herself in the basement of a man who says he's saved her life from a chemical attack that has left the outside uninhabitable.",
				"tagline": "Monsters come in many forms.",
				"original_title": "10 Cloverfield Lane",
				"actor_roles": {
					"Mat Vairo": "Jeremy",
					"Maya Erskine": "Darcy",
					"Ryan Martin Dwyer": "Extra Licoreria",
					"John Goodman": "Howard Stambler",
					"Suzanne Cryer": "Leslie",
					"John Gallagher Jr.": "Emmett DeWitt",
					"Douglas M. Griffin": "Driver",
					"Mary Elizabeth Winstead": "Michelle",
					"Bradley Cooper": "Ben (voice)",
					"Cindy Hogan": "Neighbor Woman"
				},
				"via_imdb": true,
				"mpaa": "PG-13",
				"via_tmdb": true,
				"directors": ["Dan Trachtenberg"],
				"titles": ["10 Cloverfield Lane", "\u0423\u043b. \u0427\u0443\u0434\u043e\u0432\u0438\u0449\u043d\u043e 10", "The Cellar", "Untitled Bad Robot Project", "Ten Cloverfield Lane", "Valencia", "\u0412\u0443\u043b. \u041c\u043e\u043d\u0441\u0442\u0440\u043e, 10", "\u041c\u043e\u043d\u0441\u0442\u0440\u043e 2", "\u79d1\u6d1b\u5f1710\u865f\u5730\u7a96", "\u0412\u0443\u043b\u0438\u0446\u044f \u041a\u043b\u043e\u0432\u0435\u0440\u0444\u0456\u043b\u0434, 10"],
				"imdb": "tt1179933",
				"year": 2016,
				"images": {
					"disc_art": [],
					"poster": ["https://images-na.ssl-images-amazon.com/images/M/MV5BMjEzMjczOTIxMV5BMl5BanBnXkFtZTgwOTUwMjI3NzE@._V1_SX300.jpg"],
					"extra_thumbs": [],
					"poster_original": ["https://image.tmdb.org/t/p/original/aeiVxTSTeGJ2ICf1iSDXkF3ivZp.jpg"],
					"landscape": [],
					"actors": {
						"Mat Vairo": "https://image.tmdb.org/t/p/w185/jwoIHRvTNiqrgpFZk9NMp6Yxz1S.jpg",
						"Maya Erskine": "https://image.tmdb.org/t/p/w185/ujJinfGkFnBKQ6mGijDa47fbJDW.jpg",
						"John Goodman": "https://image.tmdb.org/t/p/w185/mLJC7sRO3JnGkySJlwCJblvhBHm.jpg",
						"Suzanne Cryer": "https://image.tmdb.org/t/p/w185/AkMReAlA7VyazP89hmzNaZmT9WR.jpg",
						"John Gallagher Jr.": "https://image.tmdb.org/t/p/w185/2mn6gmPdFKaGBBAEMtTEk1tCVyi.jpg",
						"Douglas M. Griffin": "https://image.tmdb.org/t/p/w185/5QTBIsyxZRo21uYGtpGBxvkz6cB.jpg",
						"Mary Elizabeth Winstead": "https://image.tmdb.org/t/p/w185/7GFT1a5naPqg9WrfP5eBHjqDQ0K.jpg",
						"Bradley Cooper": "https://image.tmdb.org/t/p/w185/2daC5DeXqwkFND0xxutbnSVKN6c.jpg",
						"Cindy Hogan": "https://image.tmdb.org/t/p/w185/psxEhYc97fL6suQjsKGEdkqODG3.jpg"
					},
					"backdrop_original": ["https://image.tmdb.org/t/p/original/qEu2EJBQUNFx5mSKOCItwZm74ZE.jpg"],
					"clear_art": [],
					"logo": [],
					"banner": [],
					"backdrop": ["https://image.tmdb.org/t/p/w1280/qEu2EJBQUNFx5mSKOCItwZm74ZE.jpg"],
					"extra_fanart": []
				},
				"actors": ["John Goodman", "Mary Elizabeth Winstead", "John Gallagher Jr.", "Douglas M. Griffin"],
				"writers": ["Josh Campbell (story)", "Matthew Stuecken (story)", "Josh Campbell (screenplay)", "Matthew Stuecken (screenplay)", "Damien Chazelle (screenplay)"],
				"runtime": 103,
				"type": "movie",
				"released": "2016-03-10"
			},
			"_t": "media",
			"releases": [{
					"status": "done",
					"files": {
						"movie": ["/media/Data/Movies/10 Cloverfield Lane (2016)/10 Cloverfield Lane.mkv"]
					},
					"_id": "05469b9791fb4f3885650b32cb805ddf",
					"media_id": "57a0f4bf528b4a45bcba4de09e95bcbe",
					"_rev": "00030c24",
					"_t": "release",
					"is_3d": false,
					"last_edit": 1484054566,
					"identifier": "tt1179933.AC3.1080p",
					"quality": "1080p"
				}
			],
			"title": "10 Cloverfield Lane",
			"_rev": "00154493",
			"profile_id": null,
			"_id": "57a0f4bf528b4a45bcba4de09e95bcbe",
			"tags": [],
			"last_edit": 1474504936,
			"category_id": null,
			"type": "movie",
			"files": {
				"image_poster": ["/var/opt/couchpotato/cache/ed894bfebd1d82ec11822e6e4bd0f65a.jpg"]
			},
			"identifiers": {
				"imdb": "tt1179933"
			}
		}, { .........`

I ended up extracting the imdb IDs myself and converted it to csv to feed it to Trakt, but still would like to know what's going if you know :)

**Comment by clinton-hall** [comment]
I just committed a fix for this. Update and test again.
