### ISSUE TITLE
Slight mod request

### ISSUE THREAD

**Issue by mgaulton** [clinton-hall/CP-BackupTool#38]
I use this for backups, but thinking it might help solve another problem I have.
When importing IMDB or Trakt lists, if the movie is pre-production, it gets added to CP as "Unknown (0)" and shows in the UI as "Unknow n/a".
I'm trying to figure out a way to get the list of IDs of just these instances so I can refresh or remove them from CP, but I'm not having much success.
Would there be a way to modify this to only export the Unknown n/a / 0 entries so I can use that list to manipulate them?

**Comment by clinton-hall** [comment]
if you change 
https://github.com/clinton-hall/CP-BackupTool/blob/master/wanted.py#L69
from
```
    api_call = "movie.list/?status=active"
```
to
```
    api_call = "movie.list/?status=active&search=Unknown"
```
or maybe
```
    api_call = "movie.list/?status=active&starts_with=Unknown"
```

**Comment by mgaulton** [comment]
Awesome, thanks.
